### ISSUE TITLE
Unwanted terminal output with Carthage

### ISSUE THREAD

**Issue by tomassliz** [k0nserv/luft#23]
When I build something with Carthage I have this unwanted output in terminal:

```
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
objc[9086]: Class AspectTracker is implemented in both /Users/Deny/Library/Application Support/Developer/Shared/Xcode/Plug-ins/PreciseCoverage.xcplugin/Contents/MacOS/PreciseCoverage and /Users/Deny/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Luft.xcplugin/Contents/MacOS/Luft. One of the two will be used. Which one is undefined.
objc[9086]: Class AspectIdentifier is implemented in both /Users/Deny/Library/Application Support/Developer/Shared/Xcode/Plug-ins/PreciseCoverage.xcplugin/Contents/MacOS/PreciseCoverage and /Users/Deny/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Luft.xcplugin/Contents/MacOS/Luft. One of the two will be used. Which one is undefined.
objc[9086]: Class AspectsContainer is implemented in both /Users/Deny/Library/Application Support/Developer/Shared/Xcode/Plug-ins/PreciseCoverage.xcplugin/Contents/MacOS/PreciseCoverage and /Users/Deny/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Luft.xcplugin/Contents/MacOS/Luft. One of the two will be used. Which one is undefined.
objc[9086]: Class AspectInfo is implemented in both /Users/Deny/Library/Application Support/Developer/Shared/Xcode/Plug-ins/PreciseCoverage.xcplugin/Contents/MacOS/PreciseCoverage and /Users/Deny/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Luft.xcplugin/Contents/MacOS/Luft. One of the two will be used. Which one is undefined.
objc[9141]: Class AspectTracker is implemented in both /Users/Deny/Library/Application Support/Developer/Shared/Xcode/Plug-ins/PreciseCoverage.xcplugin/Contents/MacOS/PreciseCoverage and /Users/Deny/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Luft.xcplugin/Contents/MacOS/Luft. One of the two will be used. Which one is undefined.
objc[9141]: Class AspectIdentifier is implemented in both /Users/Deny/Library/Application Support/Developer/Shared/Xcode/Plug-ins/PreciseCoverage.xcplugin/Contents/MacOS/PreciseCoverage and /Users/Deny/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Luft.xcplugin/Contents/MacOS/Luft. One of the two will be used. Which one is undefined.
objc[9141]: Class AspectsContainer is implemented in both /Users/Deny/Library/Application Support/Developer/Shared/Xcode/Plug-ins/PreciseCoverage.xcplugin/Contents/MacOS/PreciseCoverage and /Users/Deny/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Luft.xcplugin/Contents/MacOS/Luft. One of the two will be used. Which one is undefined.
objc[9141]: Class AspectInfo is implemented in both /Users/Deny/Library/Application Support/Developer/Shared/Xcode/Plug-ins/PreciseCoverage.xcplugin/Contents/MacOS/PreciseCoverage and /Users/Deny/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Luft.xcplugin/Contents/MacOS/Luft. One of the two will be used. Which one is undefined.
```

It starts after last Xcode update. I tried to uninstall Luft plugin through Alcatraz and install it again but it didn't help.

**Comment by k0nserv** [comment]
This happens because both `Luft` and `PreciseCoverage` use  [Aspects](https://github.com/steipete/Aspects). I am not sure exactly how to prevent this collision. @zats do you have any ideas?

**Comment by zats** [comment]
hey, yes you are right regarding the reasons. It is just a warning though, and the carthage build is not affected in any way.
Any ideas what's the best practices of embedding frameworks into Xcode plugins? 🙃

**Comment by k0nserv** [comment]
> Any ideas what's the best practices of embedding frameworks into Xcode plugins? 🙃

Nope I've just dropped the files directly into the project which seems to be the most common integration option for plugins. @neonichu do you have any idea?

**Comment by neonichu** [comment]
There's just one solution, symbol prefixing. You can check neonichu/BBUDebuggerTuckAway@15c3b116a3392ba3e8897dc8da9d6902431ddf83 as an example.

**Comment by k0nserv** [comment]
Okay that makes sense, thanks :)

**Comment by zats** [comment]
Ugh, there must be a fastlane for that 😭

**Comment by k0nserv** [comment]
Should be fixed wtih #24 @tomassliz can you test again?

**Comment by tomassliz** [comment]
I think it's not fixed. I downloaded and builded actual master branch and it didn't help. It's possible to install this version with Alcatraz too?

**Comment by k0nserv** [comment]
The version should auto update in Alcatraz

**Comment by tomassliz** [comment]
I tried both ways and none of them fix this issue for me.

**Comment by k0nserv** [comment]
Did you try uninstalling and reinstalling it via Alcatraz?

**Comment by tomassliz** [comment]
Yes, I tried this.

**Comment by k0nserv** [comment]
I don't personally use Carthage, but do you have a minimal reproduction case I can try?

**Comment by tomassliz** [comment]
It's easy but you need to have Carthage installed on your machine.

Then create somewhere file named `Cartfile` and put this line into it:

```
github "Alamofire/Alamofire"
```

Then go to the same folder where you saved Cartfile and run this command:

```
$ carthage update --platform ios
```

That's all you need for reproduction.

**Comment by k0nserv** [comment]
I'll be damned, I can reproduce it too

**Comment by k0nserv** [comment]
Okay. Seems like @bogren missed a few cases in #24 I am fixing them as we speak

**Comment by k0nserv** [comment]
Okay I fixed more of the collisions in #25 and wasn't able to reproduce it myself anymore

**Comment by tomassliz** [comment]
I can't reproduce it too so good job! Thank you for fixing this 👍

**Comment by k0nserv** [comment]
Woho :tada: 

Thanks for reporting
